import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Web Gold Limited",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"overflow-x-hidden"}>
        <Script id="smartsupp-chat" strategy="afterInteractive">
          {`
            var _smartsupp = _smartsupp || {};
            _smartsupp.key = 'd7037c63f6af6904a18172dd705d30ab8273b3ce';
            window.smartsupp||(function(d) {
              var s,c,o=smartsupp=function(){ o._.push(arguments)};o._=[];
              s=d.getElementsByTagName('script')[0];c=d.createElement('script');
              c.type='text/javascript';c.charset='utf-8';c.async=true;
              c.src='https://www.smartsuppchat.com/loader.js?';s.parentNode.insertBefore(c,s);
            })(document);
          `}
        </Script>
        <ToastContainer />
        {children}
      </body>
    </html>
  );
}

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body className={"overflow-x-hidden"}>
//         {/* Smartsupp Chat Script */}
//         <Script id="smartsupp-chat" strategy="afterInteractive">
//           {`
//             var _smartsupp = _smartsupp || {};
//             _smartsupp.key = 'd7037c63f6af6904a18172dd705d30ab8273b3ce';
//             window.smartsupp||(function(d) {
//               var s,c,o=smartsupp=function(){ o._.push(arguments)};o._=[];
//               s=d.getElementsByTagName('script')[0];c=d.createElement('script');
//               c.type='text/javascript';c.charset='utf-8';c.async=true;
//               c.src='https://www.smartsuppchat.com/loader.js?';s.parentNode.insertBefore(c,s);
//             })(document);
//           `}
//         </Script>

//         <noscript>
//           Powered by <a href="https://www.smartsupp.com" target="_blank" rel="noopener noreferrer">Smartsupp</a>
//         </noscript>

//         {/* Main content */}
//         {children}
//       </body>
//     </html>
//   );
// }
