import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Web Gold Limited",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"overflow-x-hidden"}>
        <ToastContainer />
        {children}
        {/* <Link href="/support">
          <div className="  fixed bottom-8 right-8" style={{ zIndex: 1000 }}>
            <Image src={chatbot} alt="" />
          </div>
        </Link> */}
      </body>
    </html>
  );
}
